name: Publish npm packages

on:
  push:
    branches:
      - main
  workflow_dispatch:
    
jobs:
    publish_ui:
        uses: './.github/workflows/npm-publish-reusable.yml'
        with:
            name: 'react-ui'
        secrets: 
            NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    publish_hooks:
        uses: './.github/workflows/npm-publish-reusable.yml'
        with:
            name: 'react-hooks'
        secrets: 
            NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        