name: Publish npm package

on:
    workflow_call:
        inputs:
            name:
                required: true
                type: string
                description: 'Name of the package to publish'

jobs:
    publish:
        name: Publish ${{ inputs.name }}
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - name: Setup pnpm
          uses: pnpm/action-setup@v2.2.4
          with:
            version: 'latest'
        - uses: actions/setup-node@v2
          with:
            node-version: "18.x"
            registry-url: https://npm.pkg.github.com/
            cache: "pnpm"
        - name: Changelog
          id: version-bump
          uses: Enterwell/ChangelogManager-GitHub-Action@v3
          with:
            changelog-location: ./packages/${{ inputs.name }}
            should-bump-version: true
            changes-location: ./packages/${{ inputs.name }}/changes
            path-to-project-file: ./packages/${{ inputs.name }}/package.json
        - name: Commit changelog changes
          uses: EndBug/add-and-commit@v9.1.1
          with:
            message: "[skip ci] [version-bump] Automated commit for version ${{ steps.version-bump.outputs.bumped-semantic-version }}"
        - run: pnpm i --frozen-lockfile --filter=${{ inputs.name }}...
        - run: pnpm build --filter=${{ inputs.name }}...
        - run: pnpm publish --access public --filter=${{ inputs.name }}
          env:
            NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        - name: Git tags update
          run: |
            git config user.name github-actions
            git config user.email github-actions@github.com
  
            git tag "${{ inputs.name }}/v${{ steps.version-bump.outputs.bumped-semantic-version }}"
            git tag -f "${{ inputs.name }}/v${{ steps.version-bump.outputs.bumped-major-part }}" "${{ inputs.name }}/v${{ steps.version-bump.outputs.bumped-semantic-version }}"
            git tag -f "${{ inputs.name }}/v${{ steps.version-bump.outputs.bumped-major-part }}.${{ steps.version-bump.outputs.bumped-minor-part }}" "${{ inputs.name }}/v${{ steps.version-bump.outputs.bumped-semantic-version }}"
  
            git push -f --tags
        - name: Create GitHub release
          run: gh release create "${{ inputs.name }}/v${{ steps.version-bump.outputs.bumped-semantic-version }}" -n "${{ steps.version-bump.outputs.new-changes }}"
          env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}