name: Publish npm packages

on:
  push:
    branches:
      - main
  workflow_dispatch:
    
jobs:
    publish_ui:
        uses: './.github/workflows/npm-publish-reusable.yml'
        with:
            name: 'react-ui'
        secrets: inherit
    publish_hooks:
        uses: './.github/workflows/npm-publish-reusable.yml'
        with:
            name: 'react-hooks'
        secrets: inherit
        