name: Publish npm package

on:
    workflow_call:
        inputs:
            name:
                required: true
                type: string
                description: 'Name of the package to publish'
        secrets:
            NPM_TOKEN:
                required: true

jobs:
    publish:
        name: Publish ${{ inputs.name }}
        runs-on: ubuntu-latest
        concurrency: ci-${{ github.ref }}
        steps:
        - uses: actions/checkout@v4
        - name: Setup pnpm
          uses: pnpm/action-setup@v2.4.0
          with:
            version: 'latest'
        - uses: actions/setup-node@v3
          with:
            node-version: "18.x"
            cache: "pnpm"
        - name: Setup npmrc
          run: pnpm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
          env:
            NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        - run: git pull
        - name: Changelog
          id: version-bump
          uses: Enterwell/ChangelogManager-GitHub-Action@v3
          with:
            changelog-location: ./packages/${{ inputs.name }}
            should-bump-version: true
            changes-location: ./packages/${{ inputs.name }}/changes
            path-to-project-file: ./packages/${{ inputs.name }}/package.json
        - name: Commit changelog changes
          uses: EndBug/add-and-commit@v9.1.3
          with:
            message: "[skip ci] [version-bump] Automated commit for version ${{ steps.version-bump.outputs.bumped-semantic-version }}"
        - run: pnpm i --frozen-lockfile --filter=${{ inputs.name }}...
        - run: pnpm build --filter=${{ inputs.name }}...
        - run: pnpm publish --access public --filter=${{ inputs.name }} --no-git-checks
        - name: Git tags update
          run: |
            git config user.name github-actions
            git config user.email github-actions@github.com
  
            git tag "${{ inputs.name }}/v${{ steps.version-bump.outputs.bumped-semantic-version }}"
            git tag -f "${{ inputs.name }}/v${{ steps.version-bump.outputs.bumped-major-part }}" "${{ inputs.name }}/v${{ steps.version-bump.outputs.bumped-semantic-version }}"
            git tag -f "${{ inputs.name }}/v${{ steps.version-bump.outputs.bumped-major-part }}.${{ steps.version-bump.outputs.bumped-minor-part }}" "${{ inputs.name }}/v${{ steps.version-bump.outputs.bumped-semantic-version }}"
  
            git push -f --tags
        - name: Create GitHub release
          run: gh release create "${{ inputs.name }}/v${{ steps.version-bump.outputs.bumped-semantic-version }}" -n "${{ steps.version-bump.outputs.new-changes }}"
          env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
